import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import NavBar from './NavBar';
import Footer from './Footer';

const Layout = ({children}) => (
    <>
        <Head>
            <meta charset="UTF-8" />
			<title>Inmobiliaria en React Next</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
           
		</Head>
        <Box maxWidth="1280px" m="auto">
            <header>
                <NavBar></NavBar>
            </header>
            <main>
                {children}
            </main>
            <footer>
                <Footer></Footer>
            </footer>
        </Box>
    </>
);

export default Layout;